### ISSUE TITLE
No ik solution error

### ISSUE THREAD

**Issue by titouanlh** [PilzDE/pilz_industrial_motion#314] opened 2020-08-21 10:24 UTC
Hi,
First, i'd like to thank you for your hard work around this project.
I tried to implement your trajectory generation package as a command planner.
I followed the following steps : 

-  Added the pilz capabilities to my move_group launchfile
- Set the planning pipeline to pilz_command_planner_planning_pipeline in my move_group launchfile
- Loaded joint and cartesian limits in the param server

When I load my workcell, I can plan using Rviz with your planner but when I want to use the MotionPlanRequest, I get the following error : NO_IK_SOLUTION. I tried several positions, always reachable by the robot, but I always get the error.

Here is my motion plan request : I wan't to move "tool0" fron "manipulator" group at "pose" in base_link using PTP.
```
          planning_interface::MotionPlanRequest req;
          planning_interface::MotionPlanResponse res;
          geometry_msgs::PoseStamped poseGoal;
          poseGoal.header.frame_id="base_link";
          poseGoal.pose = pose;
          req.planner_id="PTP";
          req.group_name="manipulator";
          req.allowed_planning_time = 10.0;
          req.num_planning_attempts = 10;
          req.max_velocity_scaling_factor=1;
          req.max_acceleration_scaling_factor=1;
          moveit_msgs::Constraints poseGoalConstraints = kinematic_constraints::constructGoalConstraints("tool0",poseGoal);
          req.goal_constraints.push_back(poseGoalConstraints);
          plan_req_pub_.publish(req);
          planning_pipeline_->generatePlan(planning_scene_,req,res);
```
The motion plan request seems good to me, maybe I have defined my planning scene the wrong way ?
Here is the code : 
```
    robot_model_loader::RobotModelLoader robot_model_loader_("robot_description");
    ...
    kinematic_model_=robot_model_loader_.getModel();
    planning_scene_ = planning_scene::PlanningScenePtr(new planning_scene::PlanningScene(kinematic_model_));
    planning_pipeline_ = planning_pipeline::PlanningPipelinePtr(new 
    planning_pipeline::PlanningPipeline(kinematic_model_,nh,"planner_plugin","request_adapters"));
    robot_state_ = robot_state::RobotStatePtr(new robot_state::RobotState(kinematic_model_));
    joint_model_group_ = robot_state_->getJointModelGroup("manipulator");
    planning_scene_->getCurrentStateNonConst().setToDefaultValues(joint_model_group_,"ready");
```

I really don't understand why motion planning is working fine in Rviz but not in my code ... Any idea ?

My robot is UR3 and my Ik solver is Kdl

Thank you

**Comment by hslusarek** [comment] 2020-09-08 12:56
Hello,

thanks for reaching out.

I tried to reproduce your problem. Before I go into more details, I wanted to ask something to one of the lines you wrote. 
You wrote:
```
planning_pipeline_ = planning_pipeline::PlanningPipelinePtr(new planning_pipeline::PlanningPipeline(kinematic_model_,nh,"planner_plugin","request_adapters"));
```
I noticed that you wrote `"planner_plugin"` as `planning_plugin_name`. The default value stated in the [ROS docu](http://docs.ros.org/melodic/api/moveit_ros_planning/html/classplanning__pipeline_1_1PlanningPipeline.html#a946d5a9d719d6e9af7875189b196e141) (which is used by us) is `"planning_plugin"`. Is the different  `planning_plugin_name` intentional? If not, this could be your problem.

If the before mentioned issue did not resolve your problem, we have to go into more detail. First, I wanted to ask if it is possible for you to provide more details about your specific configuration? Details like the following would be very helpful:
- Are you using `kinetic` or `melodic`?
- What packages are using to support the ur3?
- Can you provide us some logging output?
- Can you formulate your problem into an executable rostest?

I also wanted to ask why you are not using our `pilz_trajectory_generation/MoveGroupSequenceAction` and `pilz_trajectory_generation/MoveGroupSequenceService` capabilities? These capabilities do basically the same thing you do. 

Proactively, I did the following:
- I used the [ros-industrial/universal_robot](https://github.com/ros-industrial/universal_robot/tree/melodic-devel) repository (`melodic-devel` branch) to support the ur3.
- I extended our integrationtests to include the ur3, to investigate if our official ROS interface (represented by the `pilz_trajectory_generation/MoveGroupSequenceAction` and `pilz_trajectory_generation/MoveGroupSequenceService` capabilities) works. Therefore, I opened the PR #315. -> Result: The tests are successful on my local machine.

**Comment by titouanlh** [comment] 2020-09-08 13:22
Hello @hslusarek , thank you very much for your answer .
Unfortunately, I'm not working on this project anymore so I don't have access to the robot anymore.
However I can give you some answers  : 
- I think I copied the wrong code in the issue or I corrected my it since, because in my code the `planning_plugin_name` is set as `"planning_plugin"`. So I think we're ok, sorry for the confusion
- I used ROS melodic on Ubuntu 18 and the official UR Driver https://github.com/UniversalRobots/Universal_Robots_ROS_Driver

I also tried using your `MoveGroupSequenceService` which gave me the same error (no IK solution). To make thing as simple as possible, I even tried interracting with your planner using the movegroup interface but it didn't work either.
I did not have enought time to try trajectory generation using joint goal.
I'm sorry I can't give you any more consistent informations...

**Comment by hslusarek** [comment] 2020-09-09 08:23
Hello @titouanlh,
due to the fact that the problem is not reproducible (based on the given descriptions), we decided to close the issue. 
Please, feel free to contact us if the problem reappears.

**Closed as completed by hslusarek** 2020-09-09 08:23 UTC

**Comment by PingHsunTsai** [comment] 2021-08-24 21:39
Hello @hslusarek,
Recently, I start working on integrating the Pilz planner into the UR5 robot. By using the same driver([ros_industrial](https://github.com/ros-industrial/universal_robot), melodic) and following the guide you [posted](https://github.com/PilzDE/pilz_industrial_motion/pull/315/commits/7f989059a4f2e5d151fc70d2ba9526f385f3f2aa), few issues come up for me.
After comment out the 'end_effector' group, Rviz can't load any planner library. On the other hand, If the ur5.srdf stays the same then only LIN motion can be used.  Following is the error message of planning a simple path in Rviz with CIRC motion and PTP motion.
CIRC:
```
[ERROR] [1629840736.837612600]: No path constraint named "interim" or "center" found (found unknown constraint: "req.path_constraints.name" instead)
```
PTP:
```
[ERROR] [1629840915.737496500]: velocity limit not set for group manipulator
[ERROR] [1629840915.737943300]: Exception caught: 'velocity limit not set for group manipulator'
```
Thanks for your help

**Comment by martiniil** [comment] 2021-08-25 08:16
@PingHsunTsai The pilz planner was integrated into moveit (pilz_industrial_motion_planner). We no longer maintain the packages included here.

**Comment by PingHsunTsai** [comment] 2021-08-25 08:28
@martiniil Thanks for the quick reply. I will check if there are the similar problems [here](https://github.com/ros-planning/moveit_tutorials/blob/melodic-devel/doc/pilz_industrial_motion_planner/pilz_industrial_motion_planner.rst)!

**Comment by PingHsunTsai** [comment] 2021-08-25 08:43
@martiniil Thanks for your quick reply. Is [here ](https://github.com/ros-planning/moveit_tutorials)the right place to bring up Pilz issue?

**Comment by martiniil** [comment] 2021-08-25 15:45
> 
> 
> @martiniil Thanks for your quick reply. Is [here ](https://github.com/ros-planning/moveit_tutorials)the right place to bring up Pilz issue?

https://github.com/ros-planning/moveit/issues
