### ISSUE TITLE
Integrate PyTest coverage in Travis-CI 

### ISSUE THREAD

**Issue by hslusarek** [PilzDE/pilz_industrial_motion#275] opened 2020-05-12 08:44 UTC
Currently the coverage can only be run manually via [run-coverage.sh](https://github.com/PilzDE/pilz_teach/blob/melodic-devel/pilz_teleoperation/test/unittests/run-coverage.sh). In this task the coverage has to be included into the CI.

**Comment by jschleicher** [comment] 2020-06-09 09:24
Duplicate of #289. Closing here.

**Closed as completed by jschleicher** 2020-06-09 09:24 UTC
Labels: enhancement
